@echo off
echo Adding SEO changes...
git add .
echo Committing...
git commit -m "seo: add SSR pre-rendering, favicon, og-image, and fix Googlebot indexing"
echo Pushing to production...
git push origin main
echo Done!
