@echo off
echo Adding SEO changes...
git add .
echo Committing...
git commit -m "seo: improve main domain metadata and add google verification"
echo Pushing to production...
git push origin main
echo Done!
